### ISSUE TITLE
Help: Do we have any method to change window by window handle without new session

### ISSUE THREAD

**Issue by pppppino** [appium/appium-windows-driver#176]
There is a popup covered my app, do we have any method to change window by window handle? 

I know we can new capabilities(with "appTopLevelWindow"), then new driver, which means my session is stoped; However this method is not suitable for my usage scenario. So, do we have any method to do it while keep the session.

**Comment by mykola-mokhnach** [comment]
WinAppDriver has some examples for windows management APIs: https://github.com/microsoft/WinAppDriver/blob/master/Tests/WebDriverAPI/Window.cs
