### ISSUE TITLE
Help: Do we have any method to hover on element

### ISSUE THREAD

**Issue by pppppino** [appium/appium-windows-driver#177]
Do we have any method to hover on element, such as "windows: hover", then I can execute_script() to achieve it

**Comment by naeemakram** [comment]
You can use the Actions class and move your cursor to any UI element you want to hover on.
A separate "Hover" method is not available. 
You can do something like this:

``` csharp
IWebElement target = driver.findElement(By.XPath(""));
Actions actions = new Actions(driver);
actions.moveToElement(target).perform();
```

**Comment by pppppino** [comment]
@naeemakram , Thanks, I have tried the provided method above, but I got an Exception:
>       raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
E       selenium.common.exceptions.UnknownMethodException: Message: Currently only pen and touch pointer input source types are supported
E       Stacktrace:
E       UnsupportedOperationError: Currently only pen and touch pointer input source types are supported
E           at errorFromW3CJsonCode (C:\Users\QA\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:780:25)
E           at ProxyRequestError.getActualError (C:\Users\QA\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\errors.js:663:14)
E           at asyncHandler (C:\Users\QA\AppData\Roaming\npm\node_modules\appium\node_modules\appium-base-driver\lib\protocol\protocol.js:373:25)

**Comment by mykola-mokhnach** [comment]
Upgrade the driver to the most recent version and try [windows: hover](https://github.com/appium/appium-windows-driver#windows-hover) extension

**Comment by pppppino** [comment]
@mykola-mokhnach Thanks, after tried this, I got an Exception:
`selenium.common.exceptions.UnknownMethodException: Message: Unknown windows command 'hover'. Only startRecordingScreen,stopRecordingScreen,deleteFile,deleteFolder commands are supported.`

My Appium-Python-Client pip package is latest. what should I do next

**Comment by mykola-mokhnach** [comment]
Make sure you use the driver supplied with Appium 2. Version 1 is not supported anymore

**Comment by pppppino** [comment]
@mykola-mokhnach 
Hi, I tried [windows: hover](https://github.com/appium/appium-windows-driver#windows-hover),
`self.driver.execute_script('windows: hover',
                                       {"startElementId": ele.id})`, then I got an exception:
`selenium.common.exceptions.InvalidArgumentException: Message: Starting hover point: Either element identifier or absolute coordinates must be provided`
I just want to hover on one element, which argument should I use?

**Comment by mykola-mokhnach** [comment]
I assume in order to emulate hover start and end coordinates must be different, even if this is the same element.

Also, I need the full server log to be able to investigate actual issues. Exception messages are not enough.

**Comment by mykola-mokhnach** [comment]
> I assume in order to emulate hover start and end coordinates must be different, even if this is the same element.

I see the above comment has been ignored

**Comment by pppppino** [comment]
Oh, I got it, I will try it right now

**Comment by pppppino** [comment]
@mykola-mokhnach , 
Thanks a lot, Finally, I achieve it; but, I still wanna know, why we must give it an offset？

**Comment by mykola-mokhnach** [comment]
https://en.wikipedia.org/wiki/Mouseover

> In [computing](https://en.wikipedia.org/wiki/Computing), a mouseover, mouse hover or hover box is a [graphical control element](https://en.wikipedia.org/wiki/Graphical_control_element) that is activated when the [user](https://en.wikipedia.org/wiki/User_(computing)) moves or hovers the [pointer](https://en.wikipedia.org/wiki/Pointer_(user_interface)) over a trigger area, usually with a [mouse](https://en.wikipedia.org/wiki/Computer_mouse), but also possible with a [digital pen](https://en.wikipedia.org/wiki/Digital_pen).

If the trigger area is just a single point then obviously no movement happens and no hover event is registered

**Comment by dsa45632** [comment]
can this hover scroll into element if the element is not visible on the page? also, do we have to pass a start element to hover? or can we hover to element from anywhere?

**Comment by pppppino** [comment]
@dsa45632 , I think, you could get the (x, y) of the position that you wanna hover firstly, then you could hover anywhere!

**Comment by dsa45632** [comment]
> @dsa45632 , I think, you could get the (x, y) of the position that you wanna hover firstly, then you could hover anywhere!
first I need to scroll on the table to make the element visible , so my question is can this hover on the element with scrolling the table? because if I put x and y coordinates it will click on only that location but element needs to be scroll to be clicked
