### ISSUE TITLE
"virtualKeyCode" of "windows: keys" is not working

### ISSUE THREAD

**Issue by pppppino** [appium/appium-windows-driver#186]
My Env: 
Appium version: 2.0.0
windows driver: 2.9.2

I want to input "Ctrl + V" to achieve  "paste", my code:

`self.driver.execute_script('windows: keys',
                                       {"actions": [
                    {"virtualKeyCode": 0x11, "down": True},
                    {"text": "v"},
                    {"virtualKeyCode": 0x11, "down": False}
                ])`

Then only "v" was inputted, instead of the text in clipboard!

**Comment by mykola-mokhnach** [comment]
Please also attach the actual server log

**Comment by mykola-mokhnach** [comment]
You may try the following sequence (as described in https://batchloaf.wordpress.com/2012/10/18/simulating-a-ctrl-v-keystroke-in-win32-c-or-c-using-sendinput/):

```python
[
  {"virtualKeyCode": 0x11, "down": True},
  {"virtualKeyCode": 0x56, "down": True}, # V key
  {"virtualKeyCode": 0x56, "down": False},
  {"virtualKeyCode": 0x11, "down": False},
]
```

**Comment by pppppino** [comment]
@mykola-mokhnach 
Thanks, your method works well!
