### ISSUE TITLE
Driver dont start

### ISSUE THREAD

**Issue by Comeodore** [appium/appium-windows-driver#244]
Enviroment: Windows 10 Pro
Developer Mode activated
Node js - 21.6.2
NPM - 10.2.4
Appium - 2.5.1
Appium windows driver - 2.12.17 

<img width="944" alt="image" src="https://github.com/appium/appium-windows-driver/assets/144933825/32a724f3-3456-4bb2-a5cf-9c1f4148aaf8">

@KazuCocoa @mykola-mokhnach

**Comment by mykola-mokhnach** [comment]
https://github.com/appium/appium/issues/19659

**Comment by Comeodore** [comment]
@mykola-mokhnach Thanks, working on LTS version of node js
