### ISSUE TITLE
Appium Windows Driver for Windows 11

### ISSUE THREAD

**Issue by zewer** [appium/appium-windows-driver#250]
Hello Team

I see from official description this driver works only with Windows 10. But what about windows 11? Should I use this one? How stable it works?

**Comment by naeemakram** [comment]
WinAppDriver works fine on Windows 11, I have tried. It myself. The main problem is it doesn't work with Appium 5 straight away. You have to be a little investigative and creative to make it work on Appium 5. 
Apparently this project is dead.

**Comment by zewer** [comment]
> WinAppDriver works fine on Windows 11, I have tried. It myself. The main problem is it doesn't work with Appium 5 straight away. You have to be a little investigative and creative to make it work on Appium 5. Apparently this project is dead.

Thanks! Is latest version works fine? See something like that

![image](https://github.com/appium/appium-windows-driver/assets/16626874/52d5dd1f-3de9-4464-8db0-b13f7e045d16)

**Comment by zewer** [comment]
Solution
https://github.com/appium/appium/issues/19659
