### ISSUE TITLE
Have you test in Windows Arm machine?

### ISSUE THREAD

**Issue by pppppino** [appium/appium-windows-driver#261]
I found that  **windows: click** method can not work correctly in **windows arm** machine. 

when I choose **elementId** as param, It always can not click on the right location, seems have some deviation from the correct location.

I have run the same script in the same app on differ machine(Win X64, Win Arm64),  it works correctly in WinX64, and not correctly in WinArm64(have deviation ), and I have tried many element, and all have this problem.

By the way, I have tried, rightClick(button: right), doubleClick(times: 2), all have above problem.

I hope you could have a try in winArm64, I believe you will reproduce this problem.

**Comment by KazuCocoa** [comment]
I think no one in Appium team has Win machine in our regular usage. Most of our contribution is voluntary basis, so the test also depends on each person's personal working env.

It is appreciated to check if the "not working" is JS code in https://github.com/appium/appium-windows-driver (this repository) or comes from https://github.com/microsoft/WinAppDriver

**Comment by pppppino** [comment]
@KazuCocoa , Finally, I got the root cause of this issue. windows arm machine have one setting called "Scale" in "Display", which default value is "150%". if you want use "doubleClick"/"rightClick"/"Hover", you have to update it to "100%"
<img width="545" alt="473968B3-7602-40E1-9161-1DFB19C5F75E" src="https://github.com/user-attachments/assets/3013d1fa-5a26-44b9-9061-096b86d19aaf">

**Comment by jlipps** [comment]
thanks for the report!
