### ISSUE TITLE
'GET /status' cannot be proxied to WinAppDriver server because its process is not running - Windows 11

### ISSUE THREAD

**Issue by vir-r** [appium/appium-windows-driver#263]
Hi,
I would appreciate your help for the following error:
`Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: 'GET /status' cannot be proxied to WinAppDriver server because its process is not running (probably crashed). Check the Appium log for more details` 

I have the following setup (which is working fine on Windows 10):
- appium version: 2.2.1
- appium windows driver: 2.12.4
- node version: 18.18.2
- appium-java-client: 9.2.0
- selenium-api version: 4.18.0
- OS: Windows 11 PRO 

I use the following desired capabilities to start the windows application under test:
 desiredCapabilities.setCapability("appium:app", app);
 desiredCapabilities.setCapability("platformName", "Windows");
 desiredCapabilities.setCapability("appium:automationName", "Windows");

and I start the appium server automatically: 
        service = AppiumDriverLocalService.buildDefaultService();
        service.start();

Logs:
    [Appium] Welcome to Appium v2.2.1
    [Appium] Attempting to load driver windows...
    [Appium] Requiring driver at C:\Users\\.appium\node_modules\appium-windows-driver
    [Appium] Appium REST http interface listener started on http://0.0.0.0:4723
    [Appium] You can provide the following URLs in your client code to connect to this server:
    [Appium]  http://10.10.146.36:4723/
    [Appium]  http://10.10.108.36:4723/
    [Appium]  http://127.0.0.1:4723/ (only accessible from the same host)
    [Appium] Available drivers:
    [Appium]   - windows@2.12.4 (automationName 'Windows')
    [Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
    [HTTP] --> GET /status
    [HTTP] {}
    [AppiumDriver@a595] Calling AppiumDriver.getStatus() with args: []
    [AppiumDriver@a595] Responding to client with driver.getStatus() result: {"ready":true,"message":"The server is ready to accept new connections","build":{"version":"2.2.1"}}
    [HTTP] <-- GET /status 200 8 ms - 110
 --> POST /session
    [HTTP] {"capabilities":{"firstMatch":[{"appium:automationName":"Windows","appium:app":"C:\\Users\\{user}\\application.exe","platformName":"windows"}]}}
    [AppiumDriver@a595] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"appium:automationName":"Windows","appium:app":"C:\\Users\\{user}\\application.exe","platformName":"windows"}]}]
    [AppiumDriver@a595] Event 'newSessionRequested' logged at 1717494872452 (18:54:32 GMT+0900 (Japan Standard Time))
    [Appium] Attempting to find matching driver for automationName 'Windows' and platformName 'windows'
    [Appium] The 'windows' driver was installed and matched caps.
    [Appium] Will require it at C:\Users\\.appium\node_modules\appium-windows-driver
    [Appium] Requiring driver at C:\Users\\.appium\node_modules\appium-windows-driver
    [AppiumDriver@a595] Appium v2.2.1 creating new WindowsDriver (v2.12.4) session
    [AppiumDriver@a595] Checking BaseDriver versions for Appium and WindowsDriver
    [AppiumDriver@a595] Appium's BaseDriver version is 9.7.0
    [AppiumDriver@a595] WindowsDriver's BaseDriver version is 9.7.0
    [WindowsDriver@8a23] Creating session with W3C capabilities: {
    [WindowsDriver@8a23]   "alwaysMatch": {
    [WindowsDriver@8a23]     "platformName": "windows",
    [WindowsDriver@8a23]     "appium:automationName": "Windows",
    [WindowsDriver@8a23]     "appium:app": "C:\\Users\\{user}\\application.exe"
    [WindowsDriver@8a23]   },
    [WindowsDriver@8a23]   "firstMatch": [
    [WindowsDriver@8a23]     {}
    [WindowsDriver@8a23]   ]
    [WindowsDriver@8a23] }
    [WindowsDriver@8a23 (c2c3d565)] Session created with session id: c2c3d565-3fc7-4117-aa3c-94c598b3c351
    [WindowsDriver@8a23 (c2c3d565)] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
    [WindowsDriver@8a23 (c2c3d565)] Matched '/status' to command name 'getStatus'
    [WindowsDriver@8a23 (c2c3d565)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
    [WindowsDriver@8a23 (c2c3d565)] connect ECONNREFUSED 127.0.0.1:4724
    [WindowsDriver@8a23 (c2c3d565)] WinAppDriver exited with code 3221225781, si    [WindowsDriver@8a23 (c2c3d565)] Deleting WinAppDriver session
    [AppiumDriver@a595] Event 'newSessionStarted' logged at 1717494873653 (18:54:33 GMT+0900 (Japan Standard Time))
    [AppiumDriver@a595] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: 'GET /status' cannot be proxied to WinAppDriver server because its process is not running (probably crashed). Check the Appium log for more details
    [AppiumDriver@a595]     at waitMs (C:\Users\\.appium\node_modules\appium-windows-driver\lib\winappdriver.js:154:19)
    [AppiumDriver@a595]     at spin (C:\Users\\.appium\node_modules\appium-windows-driver\node_modules\asyncbox\lib\asyncbox.js:221:20)
    [AppiumDriver@a595]     at spin (C:\Users\\.appium\node_modules\appium-windows-driver\node_modules\asyncbox\lib\asyncbox.js:231:14)
    [AppiumDriver@a595]     at waitForCondition (C:\Users\\.appium\node_modules\appium-windows-driver\node_modules\asyncbox\lib\asyncbox.js:238:10)
    [AppiumDriver@a595]     at WinAppDriver.start (C:\Users\\.appium\node_modules\appium-windows-driver\lib\winappdriver.js:146:7)
    [AppiumDriver@a595]     at WindowsDriver.startWinAppDriverSession (C:\Users\\.appium\node_modules\appium-windows-driver\lib\driver.js:104:5)
    [AppiumDriver@a595]     at WindowsDriver.createSession (C:\Users\\.appium\node_modules\appium-windows-driver\lib\driver.js:92:7)
    [AppiumDriver@a595]     at AppiumDriver.createSession (C:\Users\\AppData\Roaming\npm\node_modules\appium\lib\appium.js:374:35)
    [HTTP] <-- POST /session 500 1272 ms - 1042

As I mentioned above, the same setup is used on Windows 10 where the tests are working fine;
the only difference noticed in logs is that on Windows 10, the WindowsDriver's BaseDriver version is 9.4.1 instead of 9.7.0 as on Windows 11.
P.S the username and application name are hidden intentionally

**Comment by KazuCocoa** [comment]
Did the WinAppDriver itself work on Win 11? (not with Appium)

It looks like Win 11 itself is supported by https://github.com/search?q=repo%3Amicrosoft%2FWinAppDriver+Windows+11&type=issues , but possibly you might need to report it to the WinAppDriver repo

**Comment by vir-r** [comment]
Thank you for your reply. 
Indeed, there was a problem with WinAppDriver itself (installed by appium) due to concrt140.dll missing which I fixed following the guidelines [here](https://windowsreport.com/concrt140-dll/)

Now, that WinAppDriver can be started (both manually and from cmd):
```
$ C:\\Program\ Files\\Windows\ Application\ Driver\\WinAppDriver.exe 4724/wd/hub
Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub
Press ENTER to exit.
```
I receive the following error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually - 500 status code Internal Error, as shown in the logs below

Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"appium:app":"C:\\Users\\{user}\\application.exe","appium:automationName":"Windows","platformName":"windows"}]}]
    [AppiumDriver@4011] Event 'newSessionRequested' logged at 1717669914308 (19:31:54 GMT+0900 (Japan Standard Time))
    [Appium] Attempting to find matching driver for automationName 'Windows' and platformName 'windows'
    [Appium] The 'windows' driver was installed and matched caps.
    [Appium] Will require it at C:\Users\{user}\.appium\node_modules\appium-windows-driver
    [Appium] Requiring driver at C:\Users\{user}\.appium\node_modules\appium-windows-driver
    [AppiumDriver@4011] Appium v2.2.1 creating new WindowsDriver (v2.12.4) session
    [AppiumDriver@4011] Checking BaseDriver versions for Appium and WindowsDriver
    [AppiumDriver@4011] Appium's BaseDriver version is 9.7.0
    [AppiumDriver@4011] WindowsDriver's BaseDriver version is 9.7.0
    [WindowsDriver@ae44] Creating session with W3C capabilities: {
    [WindowsDriver@ae44]   "alwaysMatch": {
    [WindowsDriver@ae44]     "platformName": "windows",
    [WindowsDriver@ae44]     "appium:app": "C:\\Users\\{user}\\application.exe",
    [WindowsDriver@ae44]     "appium:automationName": "Windows"
    [WindowsDriver@ae44]   },
    [WindowsDriver@ae44]   "firstMatch": [
    [WindowsDriver@ae44]     {}
    [WindowsDriver@ae44]   ]
    [WindowsDriver@ae44] }
    [WindowsDriver@ae44 (1d401437)] Session created with session id: 1d401437-1259-41a5-8df5-dee177645d20
    [WindowsDriver@ae44 (1d401437)] Spawning 'C:\Program Files\Windows Application Driver\WinAppDriver.exe' with args: ["4724/wd/hub"]
    [WindowsDriver@ae44 (1d401437)] Matched '/status' to command name 'getStatus'
    [WindowsDriver@ae44 (1d401437)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
    [WindowsDriver@ae44 (1d401437)] connect ECONNREFUSED 127.0.0.1:4724
    [WindowsDriver@ae44 (1d401437)] Windows Application Driver listening for requests at: http://127.0.0.1:4724/wd/hub

    [WindowsDriver@ae44 (1d401437)] Press ENTER to exit.
    [WindowsDriver@ae44 (1d401437)] Matched '/status' to command name 'getStatus'
    [WindowsDriver@ae44 (1d401437)] Proxying [GET /status] to [GET http://127.0.0.1:4724/wd/hub/status] with no body
    [WindowsDriver@ae44 (1d401437)] ==========================================

    [WindowsDriver@ae44 (1d401437)] GET /wd/hub/status HTTP/1.1


    [WindowsDriver@ae44 (1d401437)] Accept: application/json, */*


    [WindowsDriver@ae44 (1d401437)] Accept-Encoding: gzip, compress, deflate, br


    [WindowsDriver@ae44 (1d401437)] Connection: keep-alive


    [WindowsDriver@ae44 (1d401437)] Content-Type: application/json; charset=utf-8


    [WindowsDriver@ae44 (1d401437)] Host: 127.0.0.1:4724


    [WindowsDriver@ae44 (1d401437)] User-Agent: appium
    [WindowsDriver@ae44 (1d401437)] Got response with status 500: {"status":13,"value":{"error":"unknown error","message":"An unknown error occurred in the remote end while processing the command."}}
    [W3C] Matched W3C error code 'unknown error' to UnknownError
    [WindowsDriver@ae44 (1d401437)] HTTP/1.1 500 Internal Error

    [WindowsDriver@ae44 (1d401437)] WinAppDriver exited with code null, signal SIGTERM
    [AppiumDriver@4011] Event 'newSessionStarted' logged at 1717669924369 (19:32:04 GMT+0900 (Japan Standard Time))
    [AppiumDriver@4011] Encountered internal error running command: Error: WinAppDriver server is not listening within 10000ms timeout. Make sure it could be started manually
    [AppiumDriver@4011]     at WinAppDriver.start (C:\Users\{user}\.appium\node_modules\appium-windows-driver\lib\winappdriver.js:164:15)
    [AppiumDriver@4011]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
    [AppiumDriver@4011]     at WindowsDriver.startWinAppDriverSession (C:\Users\{user}\.appium\node_modules\appium-windows-driver\lib\driver.js:104:5)
    [AppiumDriver@4011]     at WindowsDriver.createSession (C:\Users\{user}\.appium\node_modules\appium-windows-driver\lib\driver.js:92:7)
    [AppiumDriver@4011]     at AppiumDriver.createSession (C:\Users\{user}\AppData\Roaming\npm\node_modules\appium\lib\appium.js:374:35)
    [HTTP] <-- POST /session 500 10092 ms - 778
