### ISSUE TITLE
Appium Java client 9.3.0 Not supporting to launch Windows Application 

### ISSUE THREAD

**Issue by aarathod** [appium/appium-windows-driver#274]
It supports only appium java client 7.3.0 or lower version and it's internally calls Selenium 3.141 version, not selenium 4.
I want runt script through selenium 4.24 maven dependency. 
Is there any way to use selenium 4.24 Dependency support Appium Windows driver.
Or can we expect this is in future.

Thanks

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium-windows-driver?tab=readme-ov-file#windows-launchapp would help
