### ISSUE TITLE
AppiumDriver.restApp() does not work on WindowsDriver

### ISSUE THREAD

**Issue by mdmamunkhan** [appium/appium-windows-driver#39]
I am testing both iOS and Windows App using AppiumDriver, my driver.resetApp() function reset app for iOSDriver but it does not work for WindowsDriver. Here is the error "UnsupportedCommand java.lang.ClassCastExcep... "

**Comment by yodurr** [comment]
Closing here - please upvote on the WinAppDriver issue board:
https://github.com/Microsoft/WinAppDriver/issues/235

Thanks.
