### ISSUE TITLE
Upgrade from 1.1

### ISSUE THREAD

**Issue by OzBob** [appium/appium-windows-driver#42]
linked to https://github.com/Microsoft/WinAppDriver/issues/469#issuecomment-408925349

Version 1.1 is currently supported:
https://github.com/appium/appium-windows-driver/blob/2e203c2f0aa016f3b16ec6c1d3a613b1c785eec9/lib/installer.js#L7

This issue is to track the progress of upgrading to later version.

'Parent' issue created in: 
https://github.com/appium/appium/issues/
and
http://discuss.appium.io/t/attempts-to-run-appium-windows-driver-fail-with-error-could-not-verify-winappdriver-install-re-run-install/16431/4

**Comment by OzBob** [comment]
raised Parent issue link: https://github.com/appium/appium/issues/11807

**Comment by yodurr** [comment]
Hi @OzBob are you still running into a verification error when installing Appium?
