### ISSUE TITLE
Difference between this repo and WAD repo? 

### ISSUE THREAD

**Issue by dotnetjunky** [appium/appium-windows-driver#53]
I wonder what the difference is between this repository and WAD repo at https://github.com/Microsoft/WinAppDriver? Which one should I contribute to?

**Comment by KazuCocoa** [comment]
Thanks.

This repository is the entry point in Appium to the WAD.
https://github.com/appium/appium-windows-driver/blob/master/lib/installer.js

```
client <-> appium server(this repository) <-proxy requests-> WAD <-> Devices
```

If your contribution will be the driver itself, WAD repo is the best.
Adding features which Appium have like https://github.com/appium/appium-windows-driver/pull/48 , this repository will be a good place.

We also have a dotnet client and other clients. They also should be good places to improve clients side.
https://github.com/appium/appium-dotnet-driver
