### ISSUE TITLE
Switching between apps

### ISSUE THREAD

**Issue by jsa34** [appium/appium-windows-driver#54]
Hello,

I am trying to automated a scenario where the following happens:

1. Internet Explorer is opened and navigates to page that downloads and executes a JNLP file
2. A Java web start GUI interface is presented and I need to switch focus to this Java form for automating.
3.  Make sure both are closed after testing.

I have tried launching the app IE and completing step 1.  This was successful, but I could not then navigate to 2 as the focus was on IE app.

I then tried a different approach with launching a driver with "app" set to "Root", to manage window sessions but cannot open apps or launch new drivers attached to this session...

Stuck!

Any ideas?

**Comment by KazuCocoa** [comment]
https://discuss.appium.io and https://github.com/microsoft/WinAppDriver are better for you, I think

**Comment by jsa34** [comment]
Thank you - will close :)
